name: CI/CD Wanderscout Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Print working directory and list files
    - name: Print working directory
      run: pwd

    - name: List files
      run: ls -R

    # Step 3: Set up JDK 17 and set JAVA_HOME
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Export JAVA_HOME
      run: echo "JAVA_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV

    # Step 4: Install Flutter
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    # Step 5: Fetch dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 6: Verify Flutter configuration
    - name: Verify Flutter configuration
      run: flutter doctor

    # Step 7: Run Flutter tests
    - name: Run Flutter tests
      run: flutter test

    # Step 8: Build the app
    - name: Build APK
      run: flutter build apk --release

    # Step 9: Archive build artifacts
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: wanderscout.apk
        path: build/app/outputs/flutter-apk/app-release.apk
